const snarkjs = require("snarkjs");
const fs = require("fs");

async function run() {
    // Hardcoded test inputs
    const input = {
        salary_amount: 250000,
        nonce: "12345678901234567890",
        recipient_address: "112233445566778899"
    };

    console.log("1. Generating proof with SnarkJS Groth16...");
    
    const startTime = Date.now();

    try {
        // Generate proof using the WASM and final ZKey generated by setup.sh
        const { proof, publicSignals } = await snarkjs.groth16.fullProve(
            input,
            "salary_commitment_js/salary_commitment.wasm",
            "salary_commitment_final.zkey"
        );

        const endTime = Date.now();
        const generationTime = (endTime - startTime) / 1000;

        console.log("2. Verifying the generated proof locally...");
        
        // Load verification key
        const vKey = JSON.parse(fs.readFileSync("verification_key.json"));
        
        // Verify proof
        const isValid = await snarkjs.groth16.verify(vKey, publicSignals, proof);

        // Required Output Format
        console.log(`Proof valid: ${isValid}`);
        console.log(`Proof generation time: ${generationTime}s`);

        // Save proof and public signals to files
        fs.writeFileSync("test_proof.json", JSON.stringify(proof, null, 2));
        fs.writeFileSync("test_public.json", JSON.stringify(publicSignals, null, 2));
        
        console.log("3. Results saved to test_proof.json and test_public.json");

    } catch (error) {
        console.error("Error during proof generation or verification:", error);
        process.exit(1);
    }
}

run().then(() => {
    process.exit(0);
});
